name: 'Publish Release'
on:
  workflow_dispatch:
    inputs:
      isSnapshot:
        description: Produce a snapshot release
        required: true
        default: true
        type: boolean
jobs:
  sbt_release:
    runs-on: ubuntu-latest
    steps:
      - uses: guardian/actions-sbt-release@pmr/wip
        with:
          fetchDepth: 0
          pgpSecret: ${{ secrets.PGP_SECRET }}
          pgpPassphrase: ${{ secrets.PGP_PASSPHRASE }}
          isSnapshot: ${{ inputs.isSnapshot }}
