name: 'Publish Release'
on:
  workflow_dispatch:
    inputs:
      isSnapshot:
        description: Produce a snapshot release
        required: true
        default: true
        type: boolean
jobs:
  sbt_release:
    runs-on: ubuntu-latest
    steps:
      - uses: guardian/actions-sbt-release@v1
        with:
          fetchDepth: 0
          pgpSecret: ${{ secrets.PGP_SECRET }}
          pgpPassphrase: ${{ secrets.PGP_PASSPHRASE }}
          sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          isSnapshot: ${{ inputs.isSnapshot }}
